POST   http://localhost:8000/api/users/auth
Content-Type: application/json

{
    "email" : "email@jdoe.com",
    "password" : "12345qwerty"
}

###

POST   http://localhost:5000/api/users/
Content-Type: application/json

{
    "name" : "Jane doe",
    "email" : "email@jdoe.com",
    "password" : "12345qwerty"
}

###

POST   http://localhost:8000/api/users/logout
Content-Type: application/json

###

GET    http://localhost:8000/api/users/profile
Content-Type: application/json

###

PUT    http://localhost:8000/api/users/profile
Content-Type: application/json